openapi: "3.0.0"
info:
  title: Cameron Slash API
  version: "1.0"
paths:
  /api/hello:
    get:
      summary: Returns JSON object
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: Your name
        - in: query
          name: age
          schema:
            type: integer
          description: Your age
      responses:
        "200":
          description: Returns HelloResponse object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloResponse"
  /api/sendsms:
    post:
      summary: Sends SMS Message
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        description: JSON object of message and numbers to send to
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SMSRequestBody"
      responses:
        "201":
          description: Successfully sent SMS message
components:
  schemas:
    HelloResponse:
      description: Returned object of name and age
      type: object
      properties:
        name:
          type: string
          description: Your name
          example: Cameron
        age:
          type: integer
          description: Your age
          example: 24
    SMSRequestBody:
      description: Request body of /sendsms
      type: object
      properties:
        messageText:
          type: string
          description: Text of sms text message
          example: Hello, World
        phoneNumbers:
          type: array
          items:
            type: string
          description: List of phone numbers to send the text message to
          example: ["13171234567", "13177654321"]
